# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fb567591ab72f36952694fbc9c5f4baa028246216472d1451eca8da67a28a93835e4236ed5291db6b5d7564c31a46acb257eda201918d0d8c4db61c9d608a7

test:
  secret_key_base: 6396a644c21a55c6319c61e2756fa85aa65117684092f36562f7aeed61aa2486659b70d147929c0833f83b9df5072486a757b6b833af4119bd4e0adce5881c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
